name: Deploy Firebase & Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Construir la app (si es necesario)
        run: npm run build

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Autenticar Firebase
        run: firebase use --add
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Desplegar a Firebase Hosting y Cloud Run
        run: firebase deploy --only hosting,run
